version: '3.0'
services:
  airflow:
    # mounted volume need write permisison
    user: root
    build: .
    restart: always
    environment:
      # load default examples or not
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # [workround] some airflow library were in user: airflow's local
      - PYTHONPATH=/home/airflow/.local/lib/python3.7/site-packages/
      # notice that sqlite default connection were changed here
      # and this change is via env which will not shows on connection UI
      - AIRFLOW_CONN_SQLITE_DEFAULT=sqlite://%2Funiqlo-sqlite%2Fsqlite_default.db

    command: airflow standalone
    volumes:
      - ./dags:/opt/airflow/dags
      - ./sqlite:/uniqlo-sqlite
    ports:
      - "8080:8080"
      - "5566:5566"
